blueprint:
  name: Robb ROB_200-025-0 wireless zigbee switch with 8 buttons (black)
  description:  |
    Blueprint for the use of the ROB_200-025-0 switch when used via the zha integration of home assistant.
    For debugging purposes, use the 'events' tab in 'developer tools' and subscribe to 'zha_event' and press 'start listening' to see the raw events.
    For each button the following is available: short press, long press (press and hold), long press release
  domain: automation
  source_url: https://github.com/rolfvreijdenberger/ha/blob/main/blueprint-device-ROB_200_025_0.yaml
  input:
    switch:
      name: switch
      description: select ROB_200-025-0 device
      selector:
        device:
          integration: zha
          model: "ROB_200-025-0"
                          
    1_1_short: #format <row>_<1/0>_<event>
      name: on button 1 short press  
      default: []
      selector:
        action: {}
    1_1_long:
      name: on button 1 long press 
      default: []
      selector:
        action: {}
    1_1_long_release:
      name: on button 1 long press release 
      default: []
      selector:
        action: {}
    2_1_short:
      name: on button 2 short press  
      default: []
      selector:
        action: {}
    2_1_long:
      name: on button 2 long press 
      default: []
      selector:
        action: {}
    2_1_long_release:
      name: on button 2 long press release 
      default: []
      selector:
        action: {}
    3_1_short:
      name: on button 3 short press  
      default: []
      selector:
        action: {}
    3_1_long:
      name: on button 3 long press 
      default: []
      selector:
        action: {}
    3_1_long_release:
      name: on button 3 long press release 
      default: []
      selector:
        action: {}
    4_1_short:
      name: on button 4 short press  
      default: []
      selector:
        action: {}
    4_1_long:
      name: on button 4 long press 
      default: []
      selector:
        action: {}
    4_1_long_release:
      name: on button 4 long press release 
      default: []
      selector:
        action: {}


    1_0_short:
      name: off button 1 short press  
      default: []
      selector:
        action: {}
    1_0_long:
      name: off button 1 long press 
      default: []
      selector:
        action: {}
    1_0_long_release:
      name: off button 1 long press release 
      default: []
      selector:
        action: {}
    2_0_short:
      name: off button 2 short press  
      default: []
      selector:
        action: {}
    2_0_long:
      name: off button 2 long press 
      default: []
      selector:
        action: {}
    2_0_long_release:
      name: off button 2 long press release 
      default: []
      selector:
        action: {}
    3_0_short:
      name: off button 3 short press  
      default: []
      selector:
        action: {}
    3_0_long:
      name: off button 3 long press 
      default: []
      selector:
        action: {}
    3_0_long_release:
      name: off button 3 long press release 
      default: []
      selector:
        action: {}
    4_0_short:
      name: off button 4 short press  
      default: []
      selector:
        action: {}
    4_0_long:
      name: off button 4 long press 
      default: []
      selector:
        action: {}
    4_0_long_release:
      name: off button 4 long press release 
      default: []
      selector:
        action: {}



mode: restart
max_exceeded: silent
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input "switch"
  
action:
  - variables:
      endpoint_id: '{{ trigger.event.data.endpoint_id }}'
      command: '{{ trigger.event.data.command }}'
  - choose:
      - conditions:
          - "{{ command == 'on' }}"
        sequence: !input "{{ endpoint_id }}_1_short"
      - conditions:
          - "{{ command == 'off' }}"
        sequence: !input "{{ endpoint_id }}_1_short"
      - conditions:
          - "{{ command == 'move_with_on_off' }}"
        sequence: !input "{{ endpoint_id }}_1_long"
      - conditions:
          - "{{ command == 'stop_with_on_off' }}"
        sequence: !input "{{ endpoint_id }}_1_long_release"
      - conditions:
          - "{{ command == 'move' }}"
        sequence: !input "{{ endpoint_id }}_0_long"
      - conditions:
          - "{{ command == 'stop' }}"
        sequence: !input "{{ endpoint_id }}_0_long_release"



