blueprint:
  name: Robb ROB_200-025-0 wireless zigbee black switch with 8 buttons.
  description:  |
    v1.0.0 blueprint for the use of the [ROB_200-025-0](https://www.robbshop.nl/draadloze-zigbee-schakelaar-met-8-knoppen-zwart) switch when used via the zha integration of home assistant.
    For each button the following is available: short press, long press (press and hold), long press release.    
    For debugging purposes, use the 'events' tab in 'developer tools' and subscribe to 'zha_event' and press 'start listening' to see the raw events.  
  domain: automation
  homeassistant:
    min_version: 2024.8.0
  author: Rolf Vreijdenberger. Based on other implementation by https://github.com/Bekkie/ha-blueprints
  source_url: https://github.com/rolfvreijdenberger/ha/blob/main/blueprint-device-ROB_200_025_0.yaml
  input:
    switch_selector:
      name: select the switch
      description: the Robb device can be selected here (from the zha integration) for which you want to define the actions for each button presssand release.
      icon: mdi:numeric-8-box-multiple-outline
      input:
        switch:
          name: switch
          description: select ROB_200-025-0 device (switch)
          selector:
            device:
              integration: zha
              model: ROB_200-025-0
              multiple: false
          
    # collapsible sections for all buttons   
    row_1_on:
      name: first row 'on' button
      description: all actions for the 'on' button of the first row.
      icon: mdi:power-cycle
      collapsed: true
      input:
        1_1_short:
          name: on button short press
          default: []
          selector:
            action: {}
        1_1_long:
          name: on button long press
          default: []
          selector:
            action: {}
        1_1_long_release:
          name: on button long press release
          default: []
          selector:
            action: {}
            
    row_2_on:
      name: second row 'on' button
      description: all actions for the 'on' button of the second row
      icon: mdi:power-cycle
      collapsed: true
      input:
        2_1_short:
          name: on button short press
          default: []
          selector:
            action: {}
        2_1_long:
          name: on button long press
          default: []
          selector:
            action: {}
        2_1_long_release:
          name: on button long press release
          default: []
          selector:
            action: {}
  
    row_3_on:
      name: third row 'on' button
      description: all actions for the 'on' button of the third row
      icon: mdi:power-cycle
      collapsed: true
      input:
        3_1_short:
          name: on button short press
          default: []
          selector:
            action: {}
        3_1_long:
          name: on button long press
          default: []
          selector:
            action: {}
        3_1_long_release:
          name: on button long press release
          default: []
          selector:
            action: {}
            
    row_4_on:
      name: fourth row 'on' button
      description: all actions for the 'on' button of the fourth row
      icon: mdi:power-cycle
      collapsed: true
      input:
        4_1_short:
          name: on button short press
          default: []
          selector:
            action: {}
        4_1_long:
          name: on button long press
          default: []
          selector:
            action: {}
        4_1_long_release:
          name: on button long press release
          default: []
          selector:
            action: {}
            
    row_1_off:
      name: first row 'off' button
      description: all actions for the 'off' button of the first row
      icon: mdi:power-off
      collapsed: true
      input:
        1_0_short:
          name: off button short press  
          default: []
          selector:
            action: {}
        1_0_long:
          name: off button long press 
          default: []
          selector:
            action: {}
        1_0_long_release:
          name: off button long press release 
          default: []
          selector:
            action: {}

    row_2_off:
      name: second row 'off' button
      description: all actions for the 'off' button of the second row
      icon: mdi:power-off
      collapsed: true
      input:
        2_0_short:
          name: off button short press  
          default: []
          selector:
            action: {}
        2_0_long:
          name: off button long press 
          default: []
          selector:
            action: {}
        2_0_long_release:
          name: off button long press release 
          default: []
          selector:
            action: {}
    row_3_off:
      name: third row 'off' button
      description: all actions for the 'off' button of the third row
      icon: mdi:power-off
      collapsed: true
      input:
        3_0_short:
          name: off button short press  
          default: []
          selector:
            action: {}
        3_0_long:
          name: off button long press 
          default: []
          selector:
            action: {}
        3_0_long_release:
          name: off button long press release 
          default: []
          selector:
            action: {}
    row_4_off:
      name: fourth row 'off' button
      description: all actions for the 'off' button of the fourth row
      icon: mdi:power-off
      collapsed: true
      input:
        4_0_short:
          name: off button short press  
          default: []
          selector:
            action: {}
        4_0_long:
          name: off button long press 
          default: []
          selector:
            action: {}
        4_0_long_release:
          name: off button long press release 
          default: []
          selector:
            action: {}



mode: restart
max_exceeded: silent
trigger:
  - platform: event
    event_type: zha_event # only trigger for zha_events
    event_data: # only trigger for the right switch, defined by the user as input.
      device_id: !input "switch"
  
action:
  - variables: # extraction of data from the zha_event
      endpoint_id: '{{ trigger.event.data.endpoint_id }}' # this is the same as the row of the buttons
      command: '{{ trigger.event.data.command }}' # the command associated with a type of press
      
  - choose:
      - conditions:
          - "{{ endpoint_id == 1 and command == 'on' }}"
        sequence: !input "1_1_short"
      - conditions:
          - "{{ endpoint_id == 2 and command == 'on' }}"
        sequence: !input "2_1_short"
      - conditions:
          - "{{ endpoint_id == 3 and command == 'on' }}"
        sequence: !input "3_1_short"
      - conditions:
          - "{{ endpoint_id == 4 and command == 'on' }}"
        sequence: !input "4_1_short"
      - conditions:
          - "{{ endpoint_id == 1 and command == 'move_with_on_off' }}"
        sequence: !input "1_1_long"
      - conditions:
          - "{{ endpoint_id == 2 and command == 'move_with_on_off' }}"
        sequence: !input "2_1_long"
      - conditions:
          - "{{ endpoint_id == 3 and command == 'move_with_on_off' }}"
        sequence: !input "3_1_long"
      - conditions:
          - "{{ endpoint_id == 4 and command == 'move_with_on_off' }}"
        sequence: !input "4_1_long"
      - conditions:
          - "{{ endpoint_id == 1 and command == 'stop_with_on_off' }}"
        sequence: !input "1_1_long_release"
      - conditions:
          - "{{ endpoint_id == 2 and command == 'stop_with_on_off' }}"
        sequence: !input "2_1_long_release"
      - conditions:
          - "{{ endpoint_id == 3 and command == 'stop_with_on_off' }}"
        sequence: !input "3_1_long_release"
      - conditions:
          - "{{ endpoint_id == 4 and command == 'stop_with_on_off' }}"
        sequence: !input "4_1_long_release"
      - conditions:
          - "{{ endpoint_id == 1 and command == 'off' }}"
        sequence: !input "1_0_short"
      - conditions:
          - "{{ endpoint_id == 2 and command == 'off' }}"
        sequence: !input "2_0_short"
      - conditions:
          - "{{ endpoint_id == 3 and command == 'off' }}"
        sequence: !input "3_0_short"
      - conditions:
          - "{{ endpoint_id == 4 and command == 'off' }}"
        sequence: !input "4_0_short"
      - conditions:
          - "{{ endpoint_id == 1 and command == 'move' }}"
        sequence: !input "1_0_long"
      - conditions:
          - "{{ endpoint_id == 2 and command == 'move' }}"
        sequence: !input "2_0_long"
      - conditions:
          - "{{ endpoint_id == 3 and command == 'move' }}"
        sequence: !input "3_0_long"
      - conditions:
          - "{{ endpoint_id == 4 and command == 'move' }}"
        sequence: !input "4_0_long"
      - conditions:
          - "{{ endpoint_id == 1 and command == 'stop' }}"
        sequence: !input "1_0_long_release"
      - conditions:
          - "{{ endpoint_id == 2 and command == 'stop' }}"
        sequence: !input "2_0_long_release"
      - conditions:
          - "{{ endpoint_id == 3 and command == 'stop' }}"
        sequence: !input "3_0_long_release"
      - conditions:
          - "{{ endpoint_id == 4 and command == 'stop' }}"
        sequence: !input "4_0_long_release"



